
services:
  multiplayer-server:
    build: ./custom-multiplayer-server
    ports:
      - "8080:8080/udp"
      - "8081:8081"
    container_name: multiplayer-server
    restart: unless-stopped
    networks:
      - multiplayer-network

networks:
  multiplayer-network:
    driver: bridge